#!/usr/bin/env python


import socket
import sys


def tcp_holepunch(source_host, source_port, dest_host, dest_port):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)

    sock.bind((source_host, int(source_port)))

    while sock.connect_ex((dest_host, int(dest_port))): pass

    return sock


def server(source_host, source_port, dest_host, dest_port):
    sock = tcp_holepunch(source_host, source_port, dest_host, dest_port)

    data = sock.recv(65535)
    print(data)

    sock.close()


def client(source_host, source_port, dest_host, dest_port):
    sock = tcp_holepunch(source_host, source_port, dest_host, dest_port)

    data = "{0}:{1}".format(dest_host, dest_port).encode("utf-8")
    sock.sendall(data)

    sock.close()


if __name__ == "__main__":

    if sys.argv[1] == "server":
        server(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
    elif sys.argv[1] == "client":
        client(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
